""" Module with S3 utils """

import os
import logging

log = logging.getLogger(__name__)

from airflow.providers.amazon.aws.hooks.s3 import S3Hook

# Функция для скачивания файла из S3
def download_file_from_s3(s3_conn_id: str, bucket_name: str, file_key: str, local_path: str):
    """ Download file form S3 to local storage """

    s3_hook = S3Hook(aws_conn_id=s3_conn_id)

    # Проверяем существование пути
    if not os.path.exists(local_path):
        os.makedirs(local_path)

    full_local_file_path = f"{local_path}/{file_key.split('/')[-1]}"

    if os.path.exists(full_local_file_path):
        log.info(f'Файл {full_local_file_path} уже существовал и был удален.')
        os.remove(full_local_file_path)

    # Скачиваем файл
    s3_hook.download_file(
        key=file_key,
        bucket_name=bucket_name,
        local_path=local_path,
        preserve_file_name=True,
        use_autogenerated_subdir=False,
    )

    log.info(f"Файл успешно сохранён в {full_local_file_path}")